Q.1

In [1]:
#(a) reverse
import numpy as np
arr=np.array([1, 2, 3, 6, 4, 5])
b=np.flip(arr)
print(b)

[5 4 6 3 2 1]


In [3]:
#(b) flatten
arr=np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat_arr=arr.flatten()
print(flat_arr)
flat_arr1=arr.ravel()
print(flat_arr1)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [4]:
#(c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

comp=np.array_equal(arr1, arr2)
print(comp)

True


In [42]:
#(d)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
val_x = np.bincount(x).argmax()
indices_x = np.where(x == val_x)
print("Most frequent in x:", val_x, "| Indices:", indices_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
counts_y = np.bincount(y)
max_count_y = np.max(counts_y)
most_freq_vals_y = np.where(counts_y == max_count_y)[0]
indices_y = {val: np.where(y == val)[0] for val in most_freq_vals_y}

print("\nMost frequent in y:", most_freq_vals_y)
for val, idx in indices_y.items():
    print(f"Value {val} found at indices {idx}")

Most frequent in x: 1 | Indices: (array([0, 5, 7, 8, 9]),)

Most frequent in y: [1 3]
Value 1 found at indices [0 1 2]
Value 3 found at indices [4 8 9]


In [9]:
#(e)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum=np.sum(gfg)
print(sum)
r_sum=np.sum(gfg,axis=1)
print(r_sum)
c_sum=np.sum(gfg,axis=0)
print(c_sum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [12]:
#(f)
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
diagonal_sum=np.trace(n_array)
print(diagonal_sum)
eigenvalues , eigenvector= np.linalg.eig(n_array)
print(eigenvalues)
print(eigenvector)
inverse=np.linalg.inv(n_array)
print(inverse)
determinant=np.linalg.det(n_array)
print(determinant)

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [43]:
#(g)
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
multi = np.dot(p1, q1)
cov1 = np.cov(p1, q1)
print(multi)
print(cov1)
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
multi1 = np.dot(p2, q2)
combined = np.hstack((p2, q2.T))
cov2 = np.cov(combined.T)
print(multi1)
print(cov2)

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [16]:
#(h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x, y)
print(inner_product)
outer_product = np.outer(x, y)
print(outer_product)
cartesian_product = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print(cartesian_product)

Inner Product:
 [[17 52]
 [13 62]]
Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q.2

In [20]:
#(A)
array=np.array([[1,-2,3],[-4,5,-6]])
abs_arr=np.abs(array)
print(abs_arr)

flat = array.flatten()
col_wise = array
row_wise = array.T
percentiles_flat = np.percentile(flat, [25, 50, 75])
print(percentiles_flat)
percentiles_col = np.percentile(col_wise, [25, 50, 75], axis=0)
print(percentiles_col)
percentiles_row = np.percentile(row_wise, [25, 50, 75], axis=0)
print(percentiles_row)

mean_flat = np.mean(flat)
median_flat = np.median(flat)
std_flat = np.std(flat)
print("Flattened - Mean:", mean_flat, "Median:", median_flat, "Std:", std_flat)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
print("Column-wise - Mean:", mean_col, "Median:", median_col, "Std:", std_col)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print("Row-wise - Mean:", mean_row, "Median:", median_row, "Std:", std_row)


[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Flattened - Mean: -0.5 Median: -0.5 Std: 3.8622100754188224
Column-wise - Mean: [-1.5  1.5 -1.5] Median: [-1.5  1.5 -1.5] Std: [2.5 3.5 4.5]
Row-wise - Mean: [ 0.66666667 -1.66666667] Median: [ 1. -4.] Std: [2.05480467 4.78423336]


In [22]:
#(b)
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
round_a=np.round(a)
floor_a=np.floor(a)
ceil_a=np.ceil(a)
trunc_a=np.trunc(a)
print(trunc_a)
print(round_a)
print(floor_a)
print(ceil_a)

[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]
[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]


Q.3

In [28]:
#(a)
array=np.array([10,52,62,16,16,54,453])
sort_array=np.sort(array)
print(sort_array)
sort_indices=np.argsort(array)
print(sort_indices)
smallest_4 = np.sort(array)[:4]
print(smallest_4)
largest_5 = np.sort(array)[-5:]
print(largest_5)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [30]:
#(b)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers = array[np.floor(array) == array]
print(integers)
floats = array[np.floor(array) != array]
print(floats)

[1. 2. 3. 2.]
[1.2 2.2]


Q.4

In [55]:
#(a)
import cv2

def img_to_array(path):
    img = cv2.imread(path)

    if img is None:
        print("Image not found.")
        return
    if len(img.shape) == 2:  # Gray
        np.savetxt("grayscale_image.txt", img, fmt='%d')
        print("Saved grayscale image as text.")
        gray_img = np.loadtxt("grayscale_image.txt", dtype=np.uint8)
        print("Gray Image shape:", gray_img.shape)

    else:                    # RGB
        flat_img = img.reshape(-1, 3)
        np.savetxt("rgb_image.txt", flat_img, fmt='%d')
        print("Saved RGB image as text.")
        rgb_flat = np.loadtxt("rgb_image.txt", dtype=np.uint8)
        rgb_img = rgb_flat.reshape(-1, 3)
        print("RGB Image shape (flattened):", rgb_img.shape)

img_to_array('sample.jpg')

Saved RGB image as text.
RGB Image shape (flattened): (39763152, 3)
